language: node_js
node_js:
  - 4
  - 5
notifications:
  slack:
    secure: UlkmEBI8CYjuL5RKG4XSephHhHLqN+RjSwuzDtO7eOvYi2gXT2WYlXf9RxDdSO8uOjmnyyyQC++gkAubR80017D7L/Gahfo6gXGVloDQibLNl64dICgWaolKL/GaseFO7PyDFBmS0i250QXEldXGxjhxISfy6W0m+ZuBzi/63oc=
sudo: false
